### ISSUE TITLE
Version of postgresql-server-dev on Readme

### ISSUE THREAD

**Issue by EduardoBrasil** [mezuro/kalibro_configurations#32]
What is the version of the postgresql Indicated to use on development environment ? 9.1 or 9.3 ? The reason of question is because on the Readme of prezento the Indicated version is 9.3.

**Comment by rafamanzo** [comment]
You can safely use 9.3 for all the Mezuro applications. We need to update
all the Readmes to refer to 9.3 which is Ubuntu 14.04 current version.
