### ISSUE TITLE
Ranges for Lines of Code on Radon?

### ISSUE THREAD

**Issue by danielkza** [mezuro/kalibro_configurations#48]
How can we decide the thresholds for the ranges of the LOC metric on Radon?
Using the same values as Analizo does not seem good.
@marcheing and I have found that the file with highest LOC value on the python 3 standard library is somewhere between 4 and 5 thousand.
Any ideas?

**Comment by rafamanzo** [comment]
As discussed together with all the team I agree with @pedroscocco 's idea of ranges with different values accordingly to the granularity: https://github.com/mezuro/kalibro_configurations/issues/51

**Comment by rafamanzo** [comment]
And just for the record, no way 5k lines can be good for maintenability :smile:
