### ISSUE TITLE
Weight can't be zero

### ISSUE THREAD

**Issue by danielkza** [mezuro/kalibro_configurations#49]
Can't we redefine this validation? In some cases, having weight equal to zero may be useful.
For example, the `blank lines` metric from Radon, since it does not have any meaning by itself. Is only means something when compared to the total number of lines. Therefore, assigning a range for it may be confusing.

**Comment by rafamanzo** [comment]
Agreed. We need a special case for MetricConfiguration: https://github.com/mezuro/kalibro_configurations/issues/52

(blank lines are good in python? I think that in excess they make the maintenability harder)

**Comment by danielkza** [comment]
I don't think they're particularly good or bad, but having at least a fraction of your code be blank lines means you probably have at least reasonable layout and separation between methods, classes, etc. For example, having 10 blank lines for 1000 code lines probably means something is a bit wrong.
