### ISSUE TITLE
Problem  when running setup script

### ISSUE THREAD

**Issue by lucasmoura** [mezuro/kalibro_configurations#90]
The setup script does not create the test database and it assumes that it is already created. Therefore, it is necessary to manually run:

RAILS_ENV=test ./bin/setup

Maybe the setup script should also run this step as well.

**Comment by rafamanzo** [comment]
Nice catch, this bug probably traces back to outdated `bin/setup` after several rails updates. Have a look at the latest version:

```ruby
#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file.

  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')

  # puts "\n== Copying sample files =="
  # unless File.exist?('config/database.yml')
  #   cp 'config/database.yml.sample', 'config/database.yml'
  # end

  puts "\n== Preparing database =="
  system! 'bin/rails db:setup'

  puts "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  puts "\n== Restarting application server =="
  system! 'bin/rails restart'
end
```

Specially how it use tasks for clearing logs, clearing tmp and restarting the server which address this special issue. For rails 4, you'll replace `rails` by `rake` at some lines.

**Comment by rafamanzo** [comment]
Related to https://github.com/mezuro/kalibro_configurations/issues/91

**Comment by rafamanzo** [comment]
Closed via https://github.com/mezuro/kalibro_configurations/pull/94
