### ISSUE TITLE
Error on setup script for tmp dir

### ISSUE THREAD

**Issue by lucasmoura** [mezuro/kalibro_configurations#91]
The setup script tries to touch the file tmp/restart.txt. However, it does not check if the tmp dir already exists, breaking the script if that is the case.

**Comment by lucasmoura** [comment]
@GustavoCayres

**Comment by rafamanzo** [comment]
Nice catch, this bug probably traces back to outdated `bin/setup` after several rails updates. Have a look at the latest version:

```ruby
#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file.

  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')

  # puts "\n== Copying sample files =="
  # unless File.exist?('config/database.yml')
  #   cp 'config/database.yml.sample', 'config/database.yml'
  # end

  puts "\n== Preparing database =="
  system! 'bin/rails db:setup'

  puts "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  puts "\n== Restarting application server =="
  system! 'bin/rails restart'
end
```

Specially how it use tasks for clearing logs, clearing tmp and restarting the server which address this special issue. For rails 4, you'll replace `rails` by `rake` at some lines.

**Comment by diegoamc** [comment]
Just a caveat: I think there's no restart task on rails 4.x.x.. We would have to keep touching `tmp/restart.txt`.

**Comment by rafamanzo** [comment]
Closed via https://github.com/mezuro/kalibro_configurations/pull/94
